name: kite
description: 'Kite News App'
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_widget_from_html_core: ^0.16.0
  fwfh_url_launcher: ^0.16.0
  shimmer: ^3.0.0

  # Networking
  http: ^1.4.0
  url_launcher: ^6.3.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Storage
  cached_network_image: ^3.4.1

  # JSON Serialization
  json_annotation: ^4.9.0

  # Utilities
  collection: ^1.19.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.15

  # JSON Serialization
  json_serializable: ^6.9.5

  # Linting
  flutter_lints: ^5.0.0

  # Task Runner
  melos: ^7.0.0-dev.8

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

melos:
  scripts:
    generate:
      desc: Generate code for the project
      run: dart run build_runner build --delete-conflicting-outputs
